name: llama_openai
channels:
- conda-forge
- defaults
dependencies:
- jupyterlab=3.5.3
- python=3.8.16
- pip=22.3.1
- pip:
  - openai==0.27.4
  - langchain==0.0.157
  - llama-index==0.6.21.post1



 
